
# String targetUrl = "https://jsonplaceholder.typicode.com/users";

api: 
  jsonplaceholder:
    domain: "jsonplaceholder.typicode.com"
    endpoints: 
      users: "/users"
      posts: "/posts"
      comments: "/comments"

database:
  postgres: "db_2309p_forum"

spring.datasource:
  driverClassName: "org.hibernate.dialect.PostgreSQLDialect"
  #driverClassName: "org.postgresql.Driver"
  #url: "jdbc:postgresql://localhost:5432/${database.postgres}"
  url: 'jdbc:postgresql://localhost:5432/db_2309p_forum'
  username: "postgres"
  password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update # update